[[themes]]
name = "tokyo-night"

[themes.palette]
background = "Reset"
foreground = "#c0caf5"
black = "#15161e"
blue = "#7aa2f7"
cyan = "#7dcfff"
green = "#9ece6a"
magenta = "#bb9af7"
red = "#f7768e"
white = "#a9b1d9"
yellow = "#e0af68"
bright_black = "#414868"
bright_blue = "#7aa2f7"
bright_cyan = "#7dcfff"
bright_green = "#9ece6a"
bright_magenta = "#bb9af7"
bright_red = "#f7768e"
bright_white = "#c0caf5"
bright_yellow = "#e0af68"

[[themes]]
name = "sonokai"

[themes.palette]
background = "Reset"
foreground = "#e2e2e3"
black = "#181819"
blue = "#76cce0"
cyan = "#f39660"
green = "#9ed072"
magenta = "#b39df3"
red = "#fc5d7c"
white = "#7f8490"
yellow = "#e7c664"
bright_black = "#595f6f"
bright_blue = "#85d3f2"
bright_cyan = "#f39660"
bright_green = "#a7df78"
bright_magenta = "#b39df3"
bright_red = "#ff6077"
bright_white = "#e2e2e3"
bright_yellow = "#e7c664"
