# Hyprpaper config (new syntax)

ipc = on

preload = /home/a1nu/Pictures/wallpapers/muichiro-tokito-5120x2880-16912.jpg

wallpaper {
  monitor =
  path = /home/a1nu/Pictures/wallpapers/muichiro-tokito-5120x2880-16912.jpg
  fit_mode = cover
}
