-- Generated by nwg-displays on 2026-06-25 at 12:33:17. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2880x1800@120.0",
    position = "384x0",
    scale = 1.5
})
hl.monitor({
    output = "DP-5",
    mode = "3840x2160@60.0",
    position = "2304x0",
    scale = 1.5
})
hl.monitor({
    output = "DP-6",
    mode = "3840x2160@60.0",
    position = "4864x0",
    scale = 1.5,
    transform = 3
})
